---
autologic_groups:
  'Development Team':
    groupname: 'developers'
  'UAT and Testing':
    groupname: 'uat'
  'Systems':
    groupname: 'systems'

autologic_users:
  'Bob Smith':
    username: 'bob2'
    sshkeys:
      - 'ssh-rsa AAAA...'
    department: 'developers'
    groups:
      - 'developers'
  'Michelle Jones':
    username: 'michellej'
    sshkeys:
      - 'ssh-rsa AAAA...'
    department: 'uat'
    groups:
      - 'uat'
      - 'developers'
  'Mr Jackson':
    username: 'mjackson'
    sshkeys:
      - 'ssh-rsa AAAA...'
    department: 'systems'
    groups:
      - 'systems'
  'Barry Bazz':
    username: 'bbazz'
    sshkeys:
      - 'ssh-rsa AAAA...'
    department: 'systems'
    groups:
      - 'systems'
